import { useMutation,useQueryClient } from '@tanstack/react-query';
import { useState,type FormEvent } from 'react';
import { z } from 'zod';
import { identityApiRequest } from '../api/identity-request';
import { operationHeaders } from '../api/idempotency';
import { useCurrentStaffSession } from '../auth/staff/StaffSessionBoundary';
import { Alert,Button,Card,Dialog,FormField,Select,StatusBadge,TextInput } from '../ui/primitives';
import { formatCny } from './shared/format';

const orderSchema=z.object({order:z.object({formal_order_id:z.string(),amazon_order_number:z.string(),buyer_customer_id:z.string(),seller_organization_id:z.string(),marketplace_code:z.string(),product_name:z.string(),confirmed_at:z.number().int(),marketplace_business_date:z.string().nullable(),review_case_id:z.string().nullable(),has_refund_obligation:z.boolean(),advance_net_cny_fen:z.string(),operational_state:z.string()}).strict()}).strict();
const eventSchema=z.object({event:z.object({event_id:z.string(),formal_order_id:z.string(),event_type:z.string(),reason:z.string(),actor_staff_id:z.string(),created_at:z.number().int()}).strict()}).strict();
const visibilitySchema=z.object({observation:z.object({observation_id:z.string(),review_case_id:z.string(),formal_order_id:z.string(),visibility_status:z.string(),note:z.string().nullable(),observed_at:z.number().int(),actor_staff_id:z.string(),created_at:z.number().int()}).strict()}).strict();
const advanceSchema=z.object({entry:z.object({entry_id:z.string(),formal_order_id:z.string(),buyer_customer_id:z.string(),entry_type:z.literal('PAYMENT'),original_payment_entry_id:z.null(),amount_cny_fen:z.string(),paid_at:z.number().int(),reversed_at:z.null(),china_business_date:z.string(),payment_channel:z.string(),note:z.string().nullable(),actor_staff_id:z.string(),created_at:z.number().int()}).strict()}).strict();
const adjustmentSchema=z.object({adjustment:z.object({adjustment_id:z.string(),formal_order_id:z.string(),source_operational_event_id:z.string().nullable(),adjustment_scope:z.string(),amount_cny_fen:z.string(),reason:z.string(),actor_staff_id:z.string(),created_at:z.number().int()}).strict()}).strict();
type Order=z.output<typeof orderSchema>['order'];
const MARKET:Record<string,string>={AMAZON_JP:'亚马逊日本站',AMAZON_US:'亚马逊美国站',COUPANG_KR:'Coupang 韩国站',RAKUTEN_JP:'乐天日本站',TIKTOK_JP:'TikTok 日本站'};

export function StaffOperatingIntegrityTools(){
  const session=useCurrentStaffSession();const role=session.role.code;if(!['owner','seller_ops','pre_sales','buyer_refund'].includes(role))return null;
  const client=useQueryClient();const [order,setOrder]=useState<Order|null>(null),[confirmAdvance,setConfirmAdvance]=useState<{body:unknown}|null>(null),[message,setMessage]=useState<string|null>(null);
  const lookup=useMutation({mutationFn:(number:string)=>identityApiRequest('staff',client,{path:`/api/staff/operating-integrity/order-lookup?amazon_order_number=${encodeURIComponent(number)}`,method:'GET',schema:orderSchema}),onSuccess:(response)=>{setOrder(response.data.order);setMessage(null);}});
  const event=useMutation({mutationFn:(body:unknown)=>write(client,`/api/staff/order-integrity/${encodeURIComponent(order!.formal_order_id)}/events`,body,eventSchema),onSuccess:(response)=>{setOrder((current)=>current?{...current,operational_state:response.data.event.event_type==='RESOLVED'?'NORMAL':response.data.event.event_type}:current);setMessage('订单异常状态已记录，原正式订单与财务快照没有被改写。');}});
  const visibility=useMutation({mutationFn:(body:unknown)=>write(client,`/api/staff/reviews/${encodeURIComponent(order!.review_case_id!)}/visibility`,body,visibilitySchema),onSuccess:()=>setMessage('评论展示状态已记录；评论原审核结果保持不变。')});
  const advance=useMutation({mutationFn:(body:unknown)=>write(client,`/api/staff/buyer-advance-principal/${encodeURIComponent(order!.formal_order_id)}/payments`,body,advanceSchema),onSuccess:(response)=>{setConfirmAdvance(null);setOrder((current)=>current?{...current,advance_net_cny_fen:(BigInt(current.advance_net_cny_fen)+BigInt(response.data.entry.amount_cny_fen)).toString()}:current);setMessage('提前返本金已记录。以后正式返款义务形成时会自动抵扣，不需要重复付款。');}});
  const adjustment=useMutation({mutationFn:(body:unknown)=>write(client,`/api/staff/order-integrity/${encodeURIComponent(order!.formal_order_id)}/financial-adjustments`,body,adjustmentSchema),onSuccess:()=>setMessage('财务补偿已追加；原财务快照未修改。')});
  function search(eventForm:FormEvent<HTMLFormElement>){eventForm.preventDefault();const value=String(new FormData(eventForm.currentTarget).get('amazon_order_number')??'').trim();if(value)lookup.mutate(value);}
  return <section className="staff-integrity-tools"><Card><div className="staff-section-toolbar"><div><h2>业务完整性工具</h2><p>处理订单确认以后发生的异常。所有操作都是追加事实，不删除、不覆盖原订单。</p></div>{order?<StatusBadge tone="processing">{MARKET[order.marketplace_code]??order.marketplace_code}</StatusBadge>:null}</div>
    <form onSubmit={search} className="historical-customer-search"><FormField label="Amazon 订单号" htmlFor="integrity-order-number"><TextInput id="integrity-order-number" name="amazon_order_number" required/></FormField><Button className="secondary" loading={lookup.isPending}>查找正式订单</Button></form>{lookup.isError?<Alert tone="danger">没有找到当前岗位有权查看的唯一正式订单。</Alert>:null}
    {order?<div className="customer-registration-success"><strong>{order.product_name}</strong><p>{order.amazon_order_number} · {MARKET[order.marketplace_code]??order.marketplace_code} · 当前订单状态：{stateLabel(order.operational_state)}</p><p>提前返本金净额：{formatCny(order.advance_net_cny_fen)} · {order.has_refund_obligation?'正式返款义务已建立':'正式返款义务尚未建立'}</p></div>:null}{message?<Alert tone="success">{message}</Alert>:null}
  </Card>
  {order&&(role==='owner'||role==='seller_ops')?<OrderEventCard busy={event.isPending} onSubmit={(body)=>event.mutate(body)}/>:null}
  {order&&(role==='owner'||role==='pre_sales')?<ReviewVisibilityCard reviewCaseId={order.review_case_id} busy={visibility.isPending} onSubmit={(body)=>visibility.mutate(body)}/>:null}
  {order&&(role==='owner'||role==='buyer_refund')?<AdvancePrincipalCard disabled={order.has_refund_obligation} busy={advance.isPending} onPrepare={(body)=>setConfirmAdvance({body})}/>:null}
  {order&&role==='owner'?<FinancialAdjustmentCard busy={adjustment.isPending} onSubmit={(body)=>adjustment.mutate(body)}/>:null}
  <Dialog open={confirmAdvance!==null} title="确认提前返本金" description="这是实际资金支付事实。确认订单、买家和金额后再记录；正式返款形成时系统会自动抵扣。" busy={advance.isPending} onClose={()=>setConfirmAdvance(null)}><div className="entry-actions"><Button className="secondary" onClick={()=>setConfirmAdvance(null)}>取消</Button><Button className="danger" loading={advance.isPending} onClick={()=>confirmAdvance&&advance.mutate(confirmAdvance.body)}>确认记录</Button></div></Dialog>
  </section>;
}
function OrderEventCard({busy,onSubmit}:{busy:boolean;onSubmit:(body:unknown)=>void}){return <Card><h3>订单后续异常</h3><form onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);onSubmit({event_type:String(data.get('event_type')),reason:String(data.get('reason'))});}}><FormField label="状态" htmlFor="order-event-type"><Select id="order-event-type" name="event_type"><option value="PLATFORM_CANCELLED">平台取消</option><option value="RETURN_REFUND">退货 / 退款</option><option value="BUSINESS_VOID">业务作废</option><option value="MANUAL_INVESTIGATION">人工调查</option><option value="RESOLVED">问题已解决 / 恢复正常</option></Select></FormField><FormField label="原因" htmlFor="order-event-reason"><TextInput id="order-event-reason" name="reason" minLength={3} required/></FormField><Button loading={busy}>记录订单状态</Button></form></Card>}
function ReviewVisibilityCard({reviewCaseId,busy,onSubmit}:{reviewCaseId:string|null;busy:boolean;onSubmit:(body:unknown)=>void}){if(!reviewCaseId)return <Card><h3>评论展示状态</h3><p>这张正式订单还没有评论记录。</p></Card>;return <Card><h3>评论展示状态</h3><p>这里记录 Amazon 当前是否仍展示评论，不会改写“当时审核通过”的事实。</p><form onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);onSubmit({visibility_status:String(data.get('visibility_status')),note:String(data.get('note')??'').trim()||null,observed_at:Date.now()});}}><FormField label="当前展示情况" htmlFor="review-visibility"><Select id="review-visibility" name="visibility_status"><option value="VISIBLE">正常显示</option><option value="NOT_VISIBLE">一直未显示</option><option value="DROPPED">掉评</option><option value="RECHECK_REQUIRED">待复查</option></Select></FormField><FormField label="备注（可选）" htmlFor="review-visibility-note"><TextInput id="review-visibility-note" name="note"/></FormField><Button loading={busy}>记录展示状态</Button></form></Card>}
function AdvancePrincipalCard({disabled,busy,onPrepare}:{disabled:boolean;busy:boolean;onPrepare:(body:unknown)=>void}){return <Card><h3>提前返本金</h3>{disabled?<Alert tone="info">这张订单已经建立正式返款义务，请回到正常“买家返款”任务处理，不再使用提前本金。</Alert>:<form onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);onPrepare({amount_cny_fen:String(data.get('amount_cny_fen')),paid_at:Date.now(),payment_channel:String(data.get('payment_channel')),note:String(data.get('note')??'').trim()||null});}}><FormField label="实际支付金额（人民币分）" htmlFor="advance-amount"><TextInput id="advance-amount" name="amount_cny_fen" inputMode="numeric" required/></FormField><FormField label="支付方式" htmlFor="advance-channel"><Select id="advance-channel" name="payment_channel"><option value="WECHAT">微信</option><option value="ALIPAY">支付宝</option><option value="BANK_TRANSFER">银行转账</option><option value="OTHER_MANUAL">其他人工方式</option></Select></FormField><FormField label="备注（可选）" htmlFor="advance-note"><TextInput id="advance-note" name="note"/></FormField><Button className="danger" loading={busy}>准备记录提前本金</Button></form>}</Card>}
function FinancialAdjustmentCard({busy,onSubmit}:{busy:boolean;onSubmit:(body:unknown)=>void}){return <Card><h3>财务补偿（仅总管理员）</h3><Alert tone="warning">输入的是“调整额”，可以为负数。它追加到经营结果，不修改原始财务快照。</Alert><form onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);onSubmit({adjustment_scope:String(data.get('scope')),amount_cny_fen:String(data.get('amount')),reason:String(data.get('reason')),source_operational_event_id:null});}}><FormField label="影响项目" htmlFor="adjustment-scope"><Select id="adjustment-scope" name="scope"><option value="PROJECTED_GROSS_PROFIT">预计利润</option><option value="COMPLETED_GROSS_PROFIT">已完成利润</option><option value="SELLER_PRINCIPAL_DUE">卖家本金应收</option><option value="SELLER_SERVICE_FEE_DUE">卖家服务费应收</option><option value="BUYER_REFUND_DUE">买家返款应付</option></Select></FormField><FormField label="调整金额（人民币分，可负数）" htmlFor="adjustment-amount"><TextInput id="adjustment-amount" name="amount" required/></FormField><FormField label="调整原因" htmlFor="adjustment-reason"><TextInput id="adjustment-reason" name="reason" minLength={3} required/></FormField><Button className="danger" loading={busy}>追加财务补偿</Button></form></Card>}
function write<T extends z.ZodType>(client:ReturnType<typeof useQueryClient>,path:string,body:unknown,schema:T){return identityApiRequest('staff',client,{path,method:'POST',schema,body,headers:operationHeaders({key:crypto.randomUUID(),body})});}
function stateLabel(value:string){return({NORMAL:'正常',PLATFORM_CANCELLED:'平台取消',RETURN_REFUND:'退货 / 退款',BUSINESS_VOID:'业务作废',MANUAL_INVESTIGATION:'人工调查'} as Record<string,string>)[value]??value;}
