export const sellerQueryKeys = Object.freeze({
  root: ['seller'] as const,
  me: ['seller', 'me'] as const,
  stores: ['seller', 'stores'] as const,
  storesPage: (cursor: string | null) => ['seller', 'stores', cursor] as const,
  products: (storeId: string | null) => ['seller', 'products', storeId ?? 'all'] as const,
  productsPage: (storeId: string | null, cursor: string | null) => ['seller', 'products', storeId ?? 'all', cursor] as const,
  applications: (storeId: string | null) => ['seller', 'applications', storeId ?? 'all'] as const,
  applicationsPage: (storeId: string | null, cursor: string | null) => ['seller', 'applications', storeId ?? 'all', cursor] as const,
  application: (id: string) => ['seller', 'application', id] as const,
  demands: (storeId: string | null) => ['seller', 'demands', storeId ?? 'all'] as const,
  demandsPage: (storeId: string | null, cursor: string | null) => ['seller', 'demands', storeId ?? 'all', cursor] as const,
  orders: (storeId: string | null) => ['seller', 'orders', storeId ?? 'all'] as const,
  ordersPage: (storeId: string | null, cursor: string | null) => ['seller', 'orders', storeId ?? 'all', cursor] as const,
  reviews: (storeId: string | null) => ['seller', 'reviews', storeId ?? 'all'] as const,
  reviewsPage: (storeId: string | null, cursor: string | null) => ['seller', 'reviews', storeId ?? 'all', cursor] as const,
  settlement: ['seller', 'settlement'] as const,
  payables: ['seller', 'settlement', 'payables'] as const,
  payablesPage: (cursor: string | null) => ['seller', 'settlement', 'payables', cursor] as const,
});
