export const buyerQueryKeys = Object.freeze({
  root: ['buyer'] as const,
  me: () => ['buyer', 'me'] as const,
  demands: (filters = '') => ['buyer', 'demands', filters] as const,
  demand: (id: string) => ['buyer', 'demands', 'detail', id] as const,
  reservations: (cursor = '') => ['buyer', 'reservations', cursor] as const,
  reservation: (id: string) => ['buyer', 'reservations', 'detail', id] as const,
  instructionState: (id: string) => ['buyer', 'instructions', id, 'state'] as const,
  instruction: (id: string, version: number) => ['buyer', 'instructions', id, 'content', version] as const,
  evidenceEligible: (cursor = '') => ['buyer', 'order-evidence', 'eligible', cursor] as const,
  evidenceList: (cursor = '') => ['buyer', 'order-evidence', 'list', cursor] as const,
  evidence: (id: string) => ['buyer', 'order-evidence', 'detail', id] as const,
  formalOrders: (filters = '') => ['buyer', 'formal-orders', filters] as const,
  formalOrder: (id: string) => ['buyer', 'formal-orders', 'detail', id] as const,
  reviewEligible: (cursor = '') => ['buyer', 'reviews', 'eligible', cursor] as const,
  reviews: (cursor = '') => ['buyer', 'reviews', 'list', cursor] as const,
  review: (id: string) => ['buyer', 'reviews', 'detail', id] as const,
  refunds: (cursor = '') => ['buyer', 'refunds', cursor] as const,
  refund: (id: string) => ['buyer', 'refunds', 'detail', id] as const,
});
