import type { FileUploadOperationState as FileTransferState } from './file-upload-operation';

export type { FileTransferState };

export type FileTransferEvent =
  | 'VALIDATE' | 'CREATE' | 'INTENT_READY' | 'UPLOAD' | 'COMPLETE' | 'VERIFIED'
  | 'RESTART' | 'CANCEL' | 'COMPENSATION' | 'DEPENDENCY' | 'FAIL';

export function fileTransferReducer(state: FileTransferState, event: FileTransferEvent): FileTransferState {
  const transitions: Readonly<Record<FileTransferState, Partial<Record<FileTransferEvent, FileTransferState>>>> = {
    IDLE: { VALIDATE: 'VALIDATING', CREATE: 'CREATING_INTENT' },
    VALIDATING: { CREATE: 'CREATING_INTENT', FAIL: 'ERROR', CANCEL: 'CANCELED' },
    CREATING_INTENT: { INTENT_READY: 'INTENT_READY', RESTART: 'RESTART_REQUIRED', FAIL: 'ERROR', CANCEL: 'CANCELED' },
    INTENT_READY: { UPLOAD: 'UPLOADING', CANCEL: 'CANCELED' }, UPLOADING: { COMPLETE: 'COMPLETING', FAIL: 'ERROR', CANCEL: 'CANCELED' },
    COMPLETING: { VERIFIED: 'VERIFIED', RESTART: 'RESTART_REQUIRED', COMPENSATION: 'FILE_COMPENSATION_REQUIRED', DEPENDENCY: 'DEPENDENCY_UNAVAILABLE', FAIL: 'ERROR', CANCEL: 'CANCELED' },
    VERIFIED: {}, RESTART_REQUIRED: { CREATE: 'CREATING_INTENT', CANCEL: 'CANCELED' },
    ERROR: { CREATE: 'CREATING_INTENT', UPLOAD: 'UPLOADING', COMPLETE: 'COMPLETING', CANCEL: 'CANCELED' },
    CANCELED: { VALIDATE: 'VALIDATING' }, FILE_COMPENSATION_REQUIRED: {},
    DEPENDENCY_UNAVAILABLE: { CREATE: 'CREATING_INTENT', UPLOAD: 'UPLOADING', COMPLETE: 'COMPLETING', CANCEL: 'CANCELED' },
  };
  return transitions[state][event] ?? state;
}
