export type FileTransferState =
  | 'IDLE' | 'CREATING_INTENT' | 'INTENT_READY' | 'UPLOADING' | 'COMPLETING' | 'VERIFIED'
  | 'CREATING_READ_INTENT' | 'READ_READY' | 'DOWNLOADING' | 'COMPLETE' | 'ERROR' | 'CANCELED'
  | 'FILE_COMPENSATION_REQUIRED' | 'DEPENDENCY_UNAVAILABLE';

export type FileTransferEvent = 'CREATE' | 'INTENT_READY' | 'UPLOAD' | 'COMPLETE' | 'VERIFIED' | 'READ' | 'READ_READY' | 'DOWNLOAD' | 'CONSUMED' | 'CANCEL' | 'COMPENSATION' | 'DEPENDENCY' | 'FAIL';

export function fileTransferReducer(state: FileTransferState, event: FileTransferEvent): FileTransferState {
  const transitions: Readonly<Record<FileTransferState, Partial<Record<FileTransferEvent, FileTransferState>>>> = {
    IDLE: { CREATE: 'CREATING_INTENT', READ: 'CREATING_READ_INTENT' }, CREATING_INTENT: { INTENT_READY: 'INTENT_READY', FAIL: 'ERROR', CANCEL: 'CANCELED' },
    INTENT_READY: { UPLOAD: 'UPLOADING', CANCEL: 'CANCELED' }, UPLOADING: { COMPLETE: 'COMPLETING', FAIL: 'ERROR', CANCEL: 'CANCELED' },
    COMPLETING: { VERIFIED: 'VERIFIED', COMPENSATION: 'FILE_COMPENSATION_REQUIRED', DEPENDENCY: 'DEPENDENCY_UNAVAILABLE', FAIL: 'ERROR' }, VERIFIED: { READ: 'CREATING_READ_INTENT' },
    CREATING_READ_INTENT: { READ_READY: 'READ_READY', FAIL: 'ERROR' }, READ_READY: { DOWNLOAD: 'DOWNLOADING', CANCEL: 'CANCELED' }, DOWNLOADING: { CONSUMED: 'COMPLETE', FAIL: 'ERROR', CANCEL: 'CANCELED' },
    COMPLETE: {}, ERROR: { CREATE: 'CREATING_INTENT', READ: 'CREATING_READ_INTENT' }, CANCELED: { CREATE: 'CREATING_INTENT', READ: 'CREATING_READ_INTENT' },
    FILE_COMPENSATION_REQUIRED: {}, DEPENDENCY_UNAVAILABLE: { CREATE: 'CREATING_INTENT', READ: 'CREATING_READ_INTENT' },
  };
  return transitions[state][event] ?? state;
}
