export const API_ERROR_CODES = [
  'VALIDATION_ERROR',
  'UNAUTHENTICATED',
  'FORBIDDEN',
  'NOT_FOUND',
  'CONFLICT',
  'VERSION_CONFLICT',
  'IDEMPOTENCY_CONFLICT',
  'REQUEST_IN_PROGRESS',
  'RATE_LIMITED',
  'DEPENDENCY_UNAVAILABLE',
  'UPLOAD_FAILED',
  'STATE_CONFLICT',
  'DUPLICATE_ORDER_NUMBER',
  'DUPLICATE_STORE',
  'STORE_NOT_FOUND',
  'PRODUCT_NOT_FOUND',
  'DUPLICATE_PRODUCT',
  'ASIN_STORE_CONFLICT',
  'PRODUCT_APPLICATION_NOT_FOUND',
  'PRODUCT_APPLICATION_ALREADY_REVIEWED',
  'PRODUCT_APPLICATION_CONFLICT',
  'DEMAND_BATCH_NOT_FOUND',
  'DEMAND_BATCH_ALREADY_REVIEWED',
  'DEMAND_BATCH_NOT_PUBLISHED',
  'DEMAND_BATCH_EXPIRED',
  'CAPACITY_FULL',
  'CUSTOMER_ALREADY_ACTIVE',
  'CUSTOMER_NOT_ACTIVE',
  'IDENTITY_REVIEW_REQUIRED',
  'INVALID_CREDENTIALS',
  'PASSWORD_CHANGE_REQUIRED',
  'SESSION_INVALID',
  'WECHAT_ID_CONFLICT',
  'SELLER_MEMBER_NOT_FOUND',
  'SELLER_MEMBER_ALREADY_ACTIVE',
] as const;

export type ApiErrorCode = typeof API_ERROR_CODES[number];

export function isApiErrorCode(value: unknown): value is ApiErrorCode {
  return typeof value === 'string'
    && (API_ERROR_CODES as readonly string[]).includes(value);
}
